import {MigrationInterface, QueryRunner} from "typeorm";

export class entities1645478207469 implements MigrationInterface {
    name = 'entities1645478207469'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "country" ("name" character varying NOT NULL, "acronym" character varying NOT NULL, CONSTRAINT "PK_61fb33f1e7c0be6a78f2d37c47a" PRIMARY KEY ("acronym"))`);
        await queryRunner.query(`CREATE TABLE "stat_atp" ("id" SERIAL NOT NULL, "round" integer NOT NULL, "firstServe1" integer, "firstServeOf1" integer, "aces1" integer, "doubleFaults1" integer, "unforcedErrors1" integer, "winningOnFirstServe1" integer, "winningOnFirstServeOf1" integer, "winningOnSecondServe1" integer, "winningOnSecondServeOf1" integer, "winners1" integer, "breakPointsConverted1" integer, "breakPointsConvertedOf1" integer, "netApproaches1" integer, "netApproachesOf1" integer, "totalPointsWon1" integer, "fastestServe1" integer, "averageFirstServeSpeed1" integer, "averageSecondServeSpeed1" integer, "firstServe2" integer, "firstServeOf2" integer, "aces2" integer, "doubleFaults2" integer, "unforcedErrors2" integer, "winningOnFirstServe2" integer, "winningOnFirstServeOf2" integer, "winningOnSecondServe2" integer, "winningOnSecondServeOf2" integer, "winners2" integer, "breakPointsConverted2" integer, "breakPointsConvertedOf2" integer, "netApproaches2" integer, "netApproachesOf2" integer, "totalPointsWon2" integer, "fastestServe2" integer, "averageFirstServeSpeed2" integer, "averageSecondServeSpeed2" integer, "rpw1" integer, "rpwOf1" integer, "rpw2" integer, "rpwOf2" integer, "mt" TIMESTAMP, "tournamentId" integer NOT NULL, "player1Id" integer NOT NULL, "player2Id" integer NOT NULL, CONSTRAINT "UQ_2c37af74e020676f4762e71f17a" UNIQUE ("player1Id", "player2Id", "tournamentId", "round"), CONSTRAINT "PK_ec5aef062aebea915467277c78a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stat_wta" ("id" SERIAL NOT NULL, "round" integer NOT NULL, "firstServe1" integer, "firstServeOf1" integer, "aces1" integer, "doubleFaults1" integer, "unforcedErrors1" integer, "winningOnFirstServe1" integer, "winningOnFirstServeOf1" integer, "winningOnSecondServe1" integer, "winningOnSecondServeOf1" integer, "winners1" integer, "breakPointsConverted1" integer, "breakPointsConvertedOf1" integer, "netApproaches1" integer, "netApproachesOf1" integer, "totalPointsWon1" integer, "fastestServe1" integer, "averageFirstServeSpeed1" integer, "averageSecondServeSpeed1" integer, "firstServe2" integer, "firstServeOf2" integer, "aces2" integer, "doubleFaults2" integer, "unforcedErrors2" integer, "winningOnFirstServe2" integer, "winningOnFirstServeOf2" integer, "winningOnSecondServe2" integer, "winningOnSecondServeOf2" integer, "winners2" integer, "breakPointsConverted2" integer, "breakPointsConvertedOf2" integer, "netApproaches2" integer, "netApproachesOf2" integer, "totalPointsWon2" integer, "fastestServe2" integer, "averageFirstServeSpeed2" integer, "averageSecondServeSpeed2" integer, "rpw1" integer, "rpwOf1" integer, "rpw2" integer, "rpwOf2" integer, "mt" TIMESTAMP, "tournamentId" integer NOT NULL, "player1Id" integer NOT NULL, "player2Id" integer NOT NULL, CONSTRAINT "UQ_bdc9ec06472ca97e3980784b9e0" UNIQUE ("player1Id", "player2Id", "tournamentId", "round"), CONSTRAINT "PK_bb6cc8be2732349d286555e457e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ep_atp" ("id" integer NOT NULL, "turnedPro" character varying NOT NULL, "weight" character varying NOT NULL, "height" character varying NOT NULL, "birthplace" character varying NOT NULL, "residence" character varying NOT NULL, "plays" character varying NOT NULL, "coach" character varying NOT NULL, "site" character varying NOT NULL, "twitter" character varying NOT NULL, "page" character varying NOT NULL, "instagram" character varying NOT NULL, "facebook" character varying NOT NULL, "last_revised" character varying NOT NULL, CONSTRAINT "PK_c1ae3e0b65230b9ed79bddcfb6a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ep_wta" ("id" integer NOT NULL, "turnedPro" character varying NOT NULL, "weight" character varying NOT NULL, "height" character varying NOT NULL, "birthplace" character varying NOT NULL, "residence" character varying NOT NULL, "plays" character varying NOT NULL, "coach" character varying NOT NULL, "site" character varying NOT NULL, "twitter" character varying NOT NULL, "page" character varying NOT NULL, "instagram" character varying NOT NULL, "facebook" character varying NOT NULL, "last_revised" character varying NOT NULL, CONSTRAINT "PK_30d56538ad24e7a8ef457bd3cc4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "player_atp" ("id" integer NOT NULL, "name" character varying NOT NULL, "birthday" TIMESTAMP, "countryAcronym" character varying, "currentRank" integer, "progress" integer, "points" integer, "hardPoints" integer, "hardTournament" integer, "clayPoints" integer, "clayTournament" integer, "grassPoints" integer, "grassTournament" integer, "carpetPoints" integer, "carterTournament" integer, "prize" integer, "ch" integer, "doublesPosition" integer, "doublesProgress" integer, "doublesPoints" integer, "ihardPoints" integer, "ihardTournament" integer, "itf" integer, CONSTRAINT "PK_d9b9c50465b081cf9c00ee40dfb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "player_wta" ("id" integer NOT NULL, "name" character varying NOT NULL, "birthday" TIMESTAMP, "countryAcronym" character varying, "currentRank" integer, "progress" integer, "points" integer, "hardPoints" integer, "hardTournament" integer, "clayPoints" integer, "clayTournament" integer, "grassPoints" integer, "grassTournament" integer, "carpetPoints" integer, "carterTournament" integer, "prize" integer, "ch" integer, "doublesPosition" integer, "doublesProgress" integer, "doublesPoints" integer, "ihardPoints" integer, "ihardTournament" integer, "itf" integer, CONSTRAINT "PK_9be2d97e36b6f64895397d5381b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "round" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_34bd959f3f4a90eb86e4ae24d2d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "game_atp" ("id" SERIAL NOT NULL, "roundId" integer NOT NULL, "result" character varying NOT NULL, "date" TIMESTAMP, "seed1" character varying, "seed2" character varying, "odd1" character varying, "odd2" character varying, "player1Id" integer NOT NULL, "player2Id" integer NOT NULL, "tournamentId" integer NOT NULL, "playersId" integer, CONSTRAINT "UQ_c89d6283b9e685c4f51517be299" UNIQUE ("player1Id", "player2Id", "tournamentId", "roundId"), CONSTRAINT "PK_cd5b6b13cf0eb86ecad21fe0270" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "game_wta" ("id" SERIAL NOT NULL, "roundId" integer NOT NULL, "result" character varying NOT NULL, "date" TIMESTAMP, "seed1" character varying, "seed2" character varying, "odd1" character varying, "odd2" character varying, "player1Id" integer NOT NULL, "player2Id" integer NOT NULL, "tournamentId" integer NOT NULL, "playersId" integer, CONSTRAINT "UQ_f258c269fd90cedc7e24376ba0a" UNIQUE ("player1Id", "player2Id", "tournamentId", "roundId"), CONSTRAINT "PK_39ebe72d5beb1e5994133c167fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rank" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_a5dfd2e605e5e4fb8578caec083" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "point" ("id" integer NOT NULL, "winner" integer NOT NULL, "finalist" integer NOT NULL, "semiFinalist" integer, "quarterFinalist" integer, "fourth" integer, "third" integer, "second" integer, "first" integer, "qualifying" integer, "qualifyingSecond" integer, "qualifyingFirst" integer, "preQualifying" integer, CONSTRAINT "PK_391f59a9491a08961038a615371" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tournament_atp" ("id" integer NOT NULL, "name" character varying NOT NULL, "courtId" integer NOT NULL, "date" TIMESTAMP WITH TIME ZONE, "rankId" integer NOT NULL, "link" integer, "countryAcronym" character varying NOT NULL, "prize" character varying, "ratingId" integer, "url" character varying, "latitude" double precision, "longitude" double precision, "site" character varying, "race" integer, "entry" integer, "singlesPrizeId" integer, "doublesMoneyId" integer, "tier" character varying, "reserveInt" integer, "reserveChar" character varying, "live" character varying, "result" character varying, CONSTRAINT "PK_769f417e3ded9fb631e93cf113b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tournament_wta" ("id" integer NOT NULL, "name" character varying NOT NULL, "courtId" integer NOT NULL, "date" TIMESTAMP WITH TIME ZONE, "rankId" integer NOT NULL, "link" integer, "countryAcronym" character varying NOT NULL, "prize" character varying, "ratingId" integer, "url" character varying, "latitude" double precision, "longitude" double precision, "site" character varying, "race" integer, "entry" integer, "singlesPrizeId" integer, "doublesMoneyId" integer, "tier" character varying, "reserveInt" integer, "reserveChar" character varying, "live" character varying, "result" character varying, CONSTRAINT "PK_e9eb6f4ccd158ecaefb5f6bad22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "court" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_d8f2118c52b422b03e0331a7b91" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "h2h_atp" ("id" SERIAL NOT NULL, "player1Wins" integer NOT NULL, "player2Wins" integer NOT NULL, "player1Id" integer NOT NULL, "player2Id" integer NOT NULL, CONSTRAINT "PK_6772aca79c60e191adda7570fa2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "h2h_wta" ("id" SERIAL NOT NULL, "player1Wins" integer NOT NULL, "player2Wins" integer NOT NULL, "player1Id" integer NOT NULL, "player2Id" integer NOT NULL, CONSTRAINT "PK_4e661fd6bc74429fb8d572b6a9c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "player_stat_atp" ("id" SERIAL NOT NULL, "data" jsonb NOT NULL, "playerId" integer, CONSTRAINT "PK_084fb99e9eb0aa08a8046c10035" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "player_stat_wta" ("id" SERIAL NOT NULL, "data" jsonb NOT NULL, "playerId" integer, CONSTRAINT "PK_f1e9762891187629b7e3d70316e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rating_atp" ("id" SERIAL NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "point" integer NOT NULL, "position" integer NOT NULL, "playerId" integer, CONSTRAINT "UQ_025bfd7987fc78dac21dade8509" UNIQUE ("date", "playerId"), CONSTRAINT "PK_e227f37bcf8c8c7a33f215f8b58" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rating_wta" ("id" SERIAL NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "point" integer NOT NULL, "position" integer NOT NULL, "playerId" integer, CONSTRAINT "UQ_3f21b9d9dc9f80130bfb3ad5512" UNIQUE ("date", "playerId"), CONSTRAINT "PK_91d6908691330874b881c6b5c3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "today_atp" ("id" SERIAL NOT NULL, "date" TIMESTAMP, "roundId" integer NOT NULL, "draw" integer NOT NULL, "result" character varying, "complete" integer, "live" character varying, "timeGame" TIMESTAMP, "reserveInt" integer, "reserveString" character varying, "odd1" character varying, "odd2" character varying, "seed1" character varying, "seed2" character varying, "player1Id" integer NOT NULL, "player2Id" integer NOT NULL, "tournamentId" integer NOT NULL, CONSTRAINT "UQ_23a3148757872e4f65ccfc87ea0" UNIQUE ("tournamentId", "player1Id", "player2Id", "roundId"), CONSTRAINT "PK_85449e3e6f4a217afc40dde02e0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "today_wta" ("id" SERIAL NOT NULL, "date" TIMESTAMP, "roundId" integer NOT NULL, "draw" integer NOT NULL, "result" character varying, "complete" integer, "live" character varying, "timeGame" TIMESTAMP, "reserveInt" integer, "reserveString" character varying, "odd1" character varying, "odd2" character varying, "seed1" character varying, "seed2" character varying, "player1Id" integer NOT NULL, "player2Id" integer NOT NULL, "tournamentId" integer NOT NULL, CONSTRAINT "UQ_216e086b35b52fb3d88f964d0fc" UNIQUE ("tournamentId", "player1Id", "player2Id", "roundId"), CONSTRAINT "PK_8f6e8f0d8d970834109efe274c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "stat_atp" ADD CONSTRAINT "FK_2922d4f130108887a91a86a6e71" FOREIGN KEY ("player1Id") REFERENCES "player_atp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stat_atp" ADD CONSTRAINT "FK_833219640d094c22b3f9e01d558" FOREIGN KEY ("player2Id") REFERENCES "player_atp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stat_atp" ADD CONSTRAINT "FK_ae0c11b9caf181fd2fd856a8e84" FOREIGN KEY ("tournamentId") REFERENCES "tournament_atp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stat_wta" ADD CONSTRAINT "FK_c71cc61e9c20d99e542fddb7966" FOREIGN KEY ("player1Id") REFERENCES "player_wta"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stat_wta" ADD CONSTRAINT "FK_f0313eb8b05eed06bd49a3a0378" FOREIGN KEY ("player2Id") REFERENCES "player_wta"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stat_wta" ADD CONSTRAINT "FK_d1cfd51e746f43d441d60ace85b" FOREIGN KEY ("tournamentId") REFERENCES "tournament_wta"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ep_atp" ADD CONSTRAINT "FK_c1ae3e0b65230b9ed79bddcfb6a" FOREIGN KEY ("id") REFERENCES "player_atp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ep_wta" ADD CONSTRAINT "FK_30d56538ad24e7a8ef457bd3cc4" FOREIGN KEY ("id") REFERENCES "player_wta"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_atp" ADD CONSTRAINT "FK_a782aab5ff6602d4961582d7f6e" FOREIGN KEY ("countryAcronym") REFERENCES "country"("acronym") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_wta" ADD CONSTRAINT "FK_5d7233c14b410eda6eaa68ea31d" FOREIGN KEY ("countryAcronym") REFERENCES "country"("acronym") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "game_atp" ADD CONSTRAINT "FK_4348fbf4328556b9f3555b2f4cf" FOREIGN KEY ("roundId") REFERENCES "round"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "game_atp" ADD CONSTRAINT "FK_8a87c474fa6a1374e8d320aa751" FOREIGN KEY ("tournamentId") REFERENCES "tournament_atp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "game_atp" ADD CONSTRAINT "FK_b76c3841636ae2f160e85c571fd" FOREIGN KEY ("player1Id") REFERENCES "player_atp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "game_atp" ADD CONSTRAINT "FK_e6889e636490dc47f317ac3f7bb" FOREIGN KEY ("player2Id") REFERENCES "player_atp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "game_atp" ADD CONSTRAINT "FK_cc066605f384ef3af11f78b1182" FOREIGN KEY ("playersId") REFERENCES "player_atp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "game_wta" ADD CONSTRAINT "FK_236b5d0394001a397df953d8e80" FOREIGN KEY ("roundId") REFERENCES "round"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "game_wta" ADD CONSTRAINT "FK_be9028a14f7af1b706812a040b3" FOREIGN KEY ("tournamentId") REFERENCES "tournament_wta"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "game_wta" ADD CONSTRAINT "FK_20d7635e1228a641661f967d0d8" FOREIGN KEY ("player1Id") REFERENCES "player_wta"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "game_wta" ADD CONSTRAINT "FK_3e4b977d475faec34cfaa7a1b67" FOREIGN KEY ("player2Id") REFERENCES "player_wta"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "game_wta" ADD CONSTRAINT "FK_b8084eac76d177c7739d91a0b3b" FOREIGN KEY ("playersId") REFERENCES "player_wta"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_atp" ADD CONSTRAINT "FK_0e3c8301f4407ca145ed048f2dc" FOREIGN KEY ("courtId") REFERENCES "court"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_atp" ADD CONSTRAINT "FK_14ce41285772c4c5e00803e62bc" FOREIGN KEY ("rankId") REFERENCES "rank"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_atp" ADD CONSTRAINT "FK_f5c7c8195d3e0e3c6368f7ed70f" FOREIGN KEY ("countryAcronym") REFERENCES "country"("acronym") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_atp" ADD CONSTRAINT "FK_a700b4ac212aa72f5800f5bed06" FOREIGN KEY ("ratingId") REFERENCES "point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_atp" ADD CONSTRAINT "FK_8a391e5510f22a0688df3d73df4" FOREIGN KEY ("singlesPrizeId") REFERENCES "point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_atp" ADD CONSTRAINT "FK_d74a9257843afd3acf4c27cde66" FOREIGN KEY ("doublesMoneyId") REFERENCES "point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_wta" ADD CONSTRAINT "FK_11a44b734037639be24f2809d73" FOREIGN KEY ("courtId") REFERENCES "court"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_wta" ADD CONSTRAINT "FK_a07e0ef87110205a318b28f6f1f" FOREIGN KEY ("rankId") REFERENCES "rank"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_wta" ADD CONSTRAINT "FK_fe8d0a43a39bd836ad6a3953ca6" FOREIGN KEY ("countryAcronym") REFERENCES "country"("acronym") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_wta" ADD CONSTRAINT "FK_afbe9a1591b9d70d2fe4e7a75e2" FOREIGN KEY ("ratingId") REFERENCES "point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_wta" ADD CONSTRAINT "FK_545bc630d52a85862eaac0f4281" FOREIGN KEY ("singlesPrizeId") REFERENCES "point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_wta" ADD CONSTRAINT "FK_fa64cc561f8914691afb9aae183" FOREIGN KEY ("doublesMoneyId") REFERENCES "point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "h2h_atp" ADD CONSTRAINT "FK_5ff6145f37b36913da641eb990d" FOREIGN KEY ("player1Id") REFERENCES "player_atp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "h2h_atp" ADD CONSTRAINT "FK_cd2bfbf494513f0d27028cc81db" FOREIGN KEY ("player2Id") REFERENCES "player_atp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "h2h_wta" ADD CONSTRAINT "FK_a61a84dc7455eaa4ce18b73cd46" FOREIGN KEY ("player1Id") REFERENCES "player_wta"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "h2h_wta" ADD CONSTRAINT "FK_f6941cb971b48aa00e9fc78f405" FOREIGN KEY ("player2Id") REFERENCES "player_wta"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_stat_atp" ADD CONSTRAINT "FK_1fb9dcb2ed341ac3921b7a40997" FOREIGN KEY ("playerId") REFERENCES "player_atp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_stat_wta" ADD CONSTRAINT "FK_e29d3d810d703b934aaac21ef98" FOREIGN KEY ("playerId") REFERENCES "player_wta"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rating_atp" ADD CONSTRAINT "FK_e27e7ce2e7e19311e4d995d8202" FOREIGN KEY ("playerId") REFERENCES "player_atp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rating_wta" ADD CONSTRAINT "FK_82019b63ab95049ff68cac53b10" FOREIGN KEY ("playerId") REFERENCES "player_wta"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "today_atp" ADD CONSTRAINT "FK_bc09446aa32c3b1e755e176d7d8" FOREIGN KEY ("roundId") REFERENCES "round"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "today_atp" ADD CONSTRAINT "FK_ce719d23314965e79e37af072bb" FOREIGN KEY ("player1Id") REFERENCES "player_atp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "today_atp" ADD CONSTRAINT "FK_7119cd98c3295e17b8e4bc073eb" FOREIGN KEY ("player2Id") REFERENCES "player_atp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "today_atp" ADD CONSTRAINT "FK_6c1f9a28542b794dfb8c75d51a9" FOREIGN KEY ("tournamentId") REFERENCES "tournament_atp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "today_wta" ADD CONSTRAINT "FK_41a6883f71e998677047797a001" FOREIGN KEY ("roundId") REFERENCES "round"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "today_wta" ADD CONSTRAINT "FK_8a6a96a9d4b286d4289765b39d0" FOREIGN KEY ("player1Id") REFERENCES "player_wta"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "today_wta" ADD CONSTRAINT "FK_6e4b50f4c27120064209ceda2c3" FOREIGN KEY ("player2Id") REFERENCES "player_wta"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "today_wta" ADD CONSTRAINT "FK_4f773f75950455a5408b26d656b" FOREIGN KEY ("tournamentId") REFERENCES "tournament_wta"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "today_wta" DROP CONSTRAINT "FK_4f773f75950455a5408b26d656b"`);
        await queryRunner.query(`ALTER TABLE "today_wta" DROP CONSTRAINT "FK_6e4b50f4c27120064209ceda2c3"`);
        await queryRunner.query(`ALTER TABLE "today_wta" DROP CONSTRAINT "FK_8a6a96a9d4b286d4289765b39d0"`);
        await queryRunner.query(`ALTER TABLE "today_wta" DROP CONSTRAINT "FK_41a6883f71e998677047797a001"`);
        await queryRunner.query(`ALTER TABLE "today_atp" DROP CONSTRAINT "FK_6c1f9a28542b794dfb8c75d51a9"`);
        await queryRunner.query(`ALTER TABLE "today_atp" DROP CONSTRAINT "FK_7119cd98c3295e17b8e4bc073eb"`);
        await queryRunner.query(`ALTER TABLE "today_atp" DROP CONSTRAINT "FK_ce719d23314965e79e37af072bb"`);
        await queryRunner.query(`ALTER TABLE "today_atp" DROP CONSTRAINT "FK_bc09446aa32c3b1e755e176d7d8"`);
        await queryRunner.query(`ALTER TABLE "rating_wta" DROP CONSTRAINT "FK_82019b63ab95049ff68cac53b10"`);
        await queryRunner.query(`ALTER TABLE "rating_atp" DROP CONSTRAINT "FK_e27e7ce2e7e19311e4d995d8202"`);
        await queryRunner.query(`ALTER TABLE "player_stat_wta" DROP CONSTRAINT "FK_e29d3d810d703b934aaac21ef98"`);
        await queryRunner.query(`ALTER TABLE "player_stat_atp" DROP CONSTRAINT "FK_1fb9dcb2ed341ac3921b7a40997"`);
        await queryRunner.query(`ALTER TABLE "h2h_wta" DROP CONSTRAINT "FK_f6941cb971b48aa00e9fc78f405"`);
        await queryRunner.query(`ALTER TABLE "h2h_wta" DROP CONSTRAINT "FK_a61a84dc7455eaa4ce18b73cd46"`);
        await queryRunner.query(`ALTER TABLE "h2h_atp" DROP CONSTRAINT "FK_cd2bfbf494513f0d27028cc81db"`);
        await queryRunner.query(`ALTER TABLE "h2h_atp" DROP CONSTRAINT "FK_5ff6145f37b36913da641eb990d"`);
        await queryRunner.query(`ALTER TABLE "tournament_wta" DROP CONSTRAINT "FK_fa64cc561f8914691afb9aae183"`);
        await queryRunner.query(`ALTER TABLE "tournament_wta" DROP CONSTRAINT "FK_545bc630d52a85862eaac0f4281"`);
        await queryRunner.query(`ALTER TABLE "tournament_wta" DROP CONSTRAINT "FK_afbe9a1591b9d70d2fe4e7a75e2"`);
        await queryRunner.query(`ALTER TABLE "tournament_wta" DROP CONSTRAINT "FK_fe8d0a43a39bd836ad6a3953ca6"`);
        await queryRunner.query(`ALTER TABLE "tournament_wta" DROP CONSTRAINT "FK_a07e0ef87110205a318b28f6f1f"`);
        await queryRunner.query(`ALTER TABLE "tournament_wta" DROP CONSTRAINT "FK_11a44b734037639be24f2809d73"`);
        await queryRunner.query(`ALTER TABLE "tournament_atp" DROP CONSTRAINT "FK_d74a9257843afd3acf4c27cde66"`);
        await queryRunner.query(`ALTER TABLE "tournament_atp" DROP CONSTRAINT "FK_8a391e5510f22a0688df3d73df4"`);
        await queryRunner.query(`ALTER TABLE "tournament_atp" DROP CONSTRAINT "FK_a700b4ac212aa72f5800f5bed06"`);
        await queryRunner.query(`ALTER TABLE "tournament_atp" DROP CONSTRAINT "FK_f5c7c8195d3e0e3c6368f7ed70f"`);
        await queryRunner.query(`ALTER TABLE "tournament_atp" DROP CONSTRAINT "FK_14ce41285772c4c5e00803e62bc"`);
        await queryRunner.query(`ALTER TABLE "tournament_atp" DROP CONSTRAINT "FK_0e3c8301f4407ca145ed048f2dc"`);
        await queryRunner.query(`ALTER TABLE "game_wta" DROP CONSTRAINT "FK_b8084eac76d177c7739d91a0b3b"`);
        await queryRunner.query(`ALTER TABLE "game_wta" DROP CONSTRAINT "FK_3e4b977d475faec34cfaa7a1b67"`);
        await queryRunner.query(`ALTER TABLE "game_wta" DROP CONSTRAINT "FK_20d7635e1228a641661f967d0d8"`);
        await queryRunner.query(`ALTER TABLE "game_wta" DROP CONSTRAINT "FK_be9028a14f7af1b706812a040b3"`);
        await queryRunner.query(`ALTER TABLE "game_wta" DROP CONSTRAINT "FK_236b5d0394001a397df953d8e80"`);
        await queryRunner.query(`ALTER TABLE "game_atp" DROP CONSTRAINT "FK_cc066605f384ef3af11f78b1182"`);
        await queryRunner.query(`ALTER TABLE "game_atp" DROP CONSTRAINT "FK_e6889e636490dc47f317ac3f7bb"`);
        await queryRunner.query(`ALTER TABLE "game_atp" DROP CONSTRAINT "FK_b76c3841636ae2f160e85c571fd"`);
        await queryRunner.query(`ALTER TABLE "game_atp" DROP CONSTRAINT "FK_8a87c474fa6a1374e8d320aa751"`);
        await queryRunner.query(`ALTER TABLE "game_atp" DROP CONSTRAINT "FK_4348fbf4328556b9f3555b2f4cf"`);
        await queryRunner.query(`ALTER TABLE "player_wta" DROP CONSTRAINT "FK_5d7233c14b410eda6eaa68ea31d"`);
        await queryRunner.query(`ALTER TABLE "player_atp" DROP CONSTRAINT "FK_a782aab5ff6602d4961582d7f6e"`);
        await queryRunner.query(`ALTER TABLE "ep_wta" DROP CONSTRAINT "FK_30d56538ad24e7a8ef457bd3cc4"`);
        await queryRunner.query(`ALTER TABLE "ep_atp" DROP CONSTRAINT "FK_c1ae3e0b65230b9ed79bddcfb6a"`);
        await queryRunner.query(`ALTER TABLE "stat_wta" DROP CONSTRAINT "FK_d1cfd51e746f43d441d60ace85b"`);
        await queryRunner.query(`ALTER TABLE "stat_wta" DROP CONSTRAINT "FK_f0313eb8b05eed06bd49a3a0378"`);
        await queryRunner.query(`ALTER TABLE "stat_wta" DROP CONSTRAINT "FK_c71cc61e9c20d99e542fddb7966"`);
        await queryRunner.query(`ALTER TABLE "stat_atp" DROP CONSTRAINT "FK_ae0c11b9caf181fd2fd856a8e84"`);
        await queryRunner.query(`ALTER TABLE "stat_atp" DROP CONSTRAINT "FK_833219640d094c22b3f9e01d558"`);
        await queryRunner.query(`ALTER TABLE "stat_atp" DROP CONSTRAINT "FK_2922d4f130108887a91a86a6e71"`);
        await queryRunner.query(`DROP TABLE "today_wta"`);
        await queryRunner.query(`DROP TABLE "today_atp"`);
        await queryRunner.query(`DROP TABLE "rating_wta"`);
        await queryRunner.query(`DROP TABLE "rating_atp"`);
        await queryRunner.query(`DROP TABLE "player_stat_wta"`);
        await queryRunner.query(`DROP TABLE "player_stat_atp"`);
        await queryRunner.query(`DROP TABLE "h2h_wta"`);
        await queryRunner.query(`DROP TABLE "h2h_atp"`);
        await queryRunner.query(`DROP TABLE "court"`);
        await queryRunner.query(`DROP TABLE "tournament_wta"`);
        await queryRunner.query(`DROP TABLE "tournament_atp"`);
        await queryRunner.query(`DROP TABLE "point"`);
        await queryRunner.query(`DROP TABLE "rank"`);
        await queryRunner.query(`DROP TABLE "game_wta"`);
        await queryRunner.query(`DROP TABLE "game_atp"`);
        await queryRunner.query(`DROP TABLE "round"`);
        await queryRunner.query(`DROP TABLE "player_wta"`);
        await queryRunner.query(`DROP TABLE "player_atp"`);
        await queryRunner.query(`DROP TABLE "ep_wta"`);
        await queryRunner.query(`DROP TABLE "ep_atp"`);
        await queryRunner.query(`DROP TABLE "stat_wta"`);
        await queryRunner.query(`DROP TABLE "stat_atp"`);
        await queryRunner.query(`DROP TABLE "country"`);
    }

}
