export const RoundSeed = [
  { id: 0, name: 'Pre-q' },
  { id: 1, name: 'q-First' },
  { id: 2, name: 'q-Second' },
  { id: 3, name: 'Qualifying' },
  { id: 4, name: 'First' },
  { id: 5, name: 'Second' },
  { id: 6, name: 'Third' },
  { id: 7, name: 'Fourth' },
  { id: 8, name: 'Robin' },
  { id: 9, name: '1/4' },
  { id: 10, name: '1/2' },
  { id: 11, name: 'Bronze' },
  { id: 12, name: 'Final' },
  { id: 13, name: 'Rubber 1' },
  { id: 14, name: 'Rubber 2' },
  { id: 15, name: 'Rubber 3' },
  { id: 16, name: 'Rubber 4' },
  { id: 17, name: 'Rubber 5' },
  { id: 20, name: 'N/A' },
];
